WARNING:tornado.access:400 POST /addUser (144.118.77.30) 5.48ms
WARNING:tornado.access:400 POST /addUser (144.118.77.30) 5.38ms
WARNING:tornado.access:404 GET /addUser%22 (35.196.75.24) 4.54ms
ERROR:tornado.application:Uncaught exception GET / (78.108.177.51)
HTTPServerRequest(protocol='http', host='127.0.0.1', method='GET', uri='/', version='HTTP/1.0', remote_ip='78.108.177.51')
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/pi/checkers/dev/back-end/RequestHandlers.py", line 209, in get
    ), 'local_files', 'checkmate-front-end', 'src', 'Register.js'), {}, to_static_markup=False,)
  File "/home/pi/.local/lib/python3.7/site-packages/react/render.py", line 15, in render_component
    raise ComponentSourceFileNotFound(path)
react.exceptions.ComponentSourceFileNotFound: /home/pi/checkers/dev/back-end/local_files/checkmate-front-end/src/Register.js
ERROR:tornado.access:500 GET / (78.108.177.51) 19.31ms
